backend:
  name: github
  repo: tu-usuario/tu-repositorio
  branch: main
  site_domain: web-de-finanzas.pages.dev
  base_url: https://web-de-finanzas.pages.dev
  auth_endpoint: /api/auth

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: blog
    label: Articles
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "pubDate", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", default: [], required: false }
      - { label: "Author", name: "author", widget: "string", default: "Admin" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Content", name: "body", widget: "markdown" }
